// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package mql5_background_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PagedRequestOptions struct {
	// cursor can be passed to retrieve the next page of results keyed by the cursor
	Cursor int32 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// page_size specifies the number of items to return in the next page
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedRequestOptions) Reset()         { *m = PagedRequestOptions{} }
func (m *PagedRequestOptions) String() string { return proto.CompactTextString(m) }
func (*PagedRequestOptions) ProtoMessage()    {}
func (*PagedRequestOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PagedRequestOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedRequestOptions.Unmarshal(m, b)
}
func (m *PagedRequestOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedRequestOptions.Marshal(b, m, deterministic)
}
func (m *PagedRequestOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedRequestOptions.Merge(m, src)
}
func (m *PagedRequestOptions) XXX_Size() int {
	return xxx_messageInfo_PagedRequestOptions.Size(m)
}
func (m *PagedRequestOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedRequestOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PagedRequestOptions proto.InternalMessageInfo

func (m *PagedRequestOptions) GetCursor() int32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *PagedRequestOptions) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PagedResponseMetadata struct {
	// A cursor that can be provided to retrieve the next page of results
	NextCursor int32 `protobuf:"varint,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Whether or not more results exist
	HasMore              bool     `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedResponseMetadata) Reset()         { *m = PagedResponseMetadata{} }
func (m *PagedResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*PagedResponseMetadata) ProtoMessage()    {}
func (*PagedResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PagedResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedResponseMetadata.Unmarshal(m, b)
}
func (m *PagedResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedResponseMetadata.Marshal(b, m, deterministic)
}
func (m *PagedResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedResponseMetadata.Merge(m, src)
}
func (m *PagedResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_PagedResponseMetadata.Size(m)
}
func (m *PagedResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PagedResponseMetadata proto.InternalMessageInfo

func (m *PagedResponseMetadata) GetNextCursor() int32 {
	if m != nil {
		return m.NextCursor
	}
	return 0
}

func (m *PagedResponseMetadata) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// *******************
// Requests
// *******************
type CreateAccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateDealRequest struct {
	Deal                 *Deal    `protobuf:"bytes,1,opt,name=deal,proto3" json:"deal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDealRequest) Reset()         { *m = CreateDealRequest{} }
func (m *CreateDealRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDealRequest) ProtoMessage()    {}
func (*CreateDealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateDealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDealRequest.Unmarshal(m, b)
}
func (m *CreateDealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDealRequest.Marshal(b, m, deterministic)
}
func (m *CreateDealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDealRequest.Merge(m, src)
}
func (m *CreateDealRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDealRequest.Size(m)
}
func (m *CreateDealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDealRequest proto.InternalMessageInfo

func (m *CreateDealRequest) GetDeal() *Deal {
	if m != nil {
		return m.Deal
	}
	return nil
}

type CreateOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type CreatePositionRequest struct {
	Position             *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePositionRequest) Reset()         { *m = CreatePositionRequest{} }
func (m *CreatePositionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePositionRequest) ProtoMessage()    {}
func (*CreatePositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *CreatePositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePositionRequest.Unmarshal(m, b)
}
func (m *CreatePositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePositionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePositionRequest.Merge(m, src)
}
func (m *CreatePositionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePositionRequest.Size(m)
}
func (m *CreatePositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePositionRequest proto.InternalMessageInfo

func (m *CreatePositionRequest) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func init() {
	proto.RegisterType((*PagedRequestOptions)(nil), "mql5_background.v1.PagedRequestOptions")
	proto.RegisterType((*PagedResponseMetadata)(nil), "mql5_background.v1.PagedResponseMetadata")
	proto.RegisterType((*CreateAccountRequest)(nil), "mql5_background.v1.CreateAccountRequest")
	proto.RegisterType((*CreateDealRequest)(nil), "mql5_background.v1.CreateDealRequest")
	proto.RegisterType((*CreateOrderRequest)(nil), "mql5_background.v1.CreateOrderRequest")
	proto.RegisterType((*CreatePositionRequest)(nil), "mql5_background.v1.CreatePositionRequest")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xd1, 0xce, 0xd2, 0x30,
	0x18, 0x86, 0xf3, 0xa3, 0xc0, 0xf8, 0x16, 0x48, 0xac, 0x42, 0x60, 0x98, 0x68, 0x96, 0x68, 0x30,
	0x31, 0x23, 0x62, 0x48, 0x3c, 0x25, 0xc8, 0x89, 0x66, 0x01, 0xb6, 0x0b, 0x58, 0xca, 0x56, 0xe7,
	0x22, 0xac, 0xa3, 0xed, 0x88, 0x7a, 0xb5, 0x5e, 0x8a, 0xdd, 0xda, 0x21, 0xf8, 0x6f, 0x67, 0xbc,
	0xed, 0xfb, 0x3d, 0xac, 0x4f, 0x0b, 0x3d, 0x9c, 0x25, 0x4e, 0xc6, 0xa8, 0xa0, 0x08, 0x9d, 0xce,
	0xc7, 0x65, 0x70, 0xc0, 0xe1, 0x8f, 0x98, 0xd1, 0x3c, 0x8d, 0x9c, 0xcb, 0x07, 0x6b, 0x1a, 0x53,
	0x1a, 0x1f, 0xc9, 0xbc, 0x6c, 0x1c, 0xf2, 0x6f, 0x73, 0x72, 0xca, 0xc4, 0x2f, 0x35, 0x60, 0xf5,
	0x71, 0x18, 0xca, 0xa2, 0xd0, 0xd1, 0xa4, 0x2c, 0x22, 0x4c, 0x07, 0x88, 0x08, 0x3e, 0xea, 0xdf,
	0x83, 0x8c, 0xf2, 0x44, 0x24, 0x34, 0x55, 0xd9, 0xfe, 0x02, 0xcf, 0x77, 0x38, 0x26, 0x91, 0x47,
	0xce, 0x39, 0xe1, 0x62, 0x9b, 0x15, 0x7b, 0x1c, 0x8d, 0xa0, 0x13, 0xe6, 0x8c, 0x53, 0x36, 0x7e,
	0x78, 0xfd, 0x30, 0x6b, 0x7b, 0x3a, 0xa1, 0x29, 0xf4, 0x32, 0x59, 0x0f, 0x78, 0xf2, 0x9b, 0x8c,
	0x5b, 0x72, 0xeb, 0x89, 0x67, 0x14, 0x0b, 0xbe, 0xcc, 0xb6, 0x0f, 0x43, 0xcd, 0xe2, 0x99, 0x84,
	0x10, 0x97, 0x08, 0x1c, 0x61, 0x81, 0xd1, 0x2b, 0x30, 0x53, 0xf2, 0x53, 0x04, 0x77, 0x48, 0x28,
	0x96, 0xd6, 0x0a, 0x3b, 0x01, 0xe3, 0x3b, 0xe6, 0xc1, 0x89, 0x32, 0x45, 0x35, 0xbc, 0xae, 0xcc,
	0xae, 0x8c, 0xb6, 0x0b, 0x2f, 0xd6, 0x8c, 0x60, 0x41, 0x56, 0xea, 0x80, 0xfa, 0x43, 0xd1, 0x12,
	0xba, 0xfa, 0xc8, 0x25, 0xcf, 0x5c, 0x4c, 0x9d, 0xc7, 0xce, 0x9c, 0x6a, 0xa8, 0xea, 0xda, 0x2b,
	0x78, 0xa6, 0x70, 0x9f, 0xa5, 0x93, 0x8a, 0xf5, 0x1e, 0x9e, 0x16, 0x8a, 0x34, 0x68, 0x5c, 0x07,
	0x2a, 0xeb, 0x65, 0xcb, 0xde, 0x00, 0x52, 0x88, 0x6d, 0xe1, 0xb8, 0x62, 0xcc, 0xa1, 0x5d, 0x3a,
	0xd7, 0x90, 0x49, 0x1d, 0x44, 0x0d, 0xa8, 0x9e, 0xbd, 0x87, 0xa1, 0xc2, 0xec, 0xf4, 0x8d, 0x54,
	0xa4, 0x4f, 0x60, 0x54, 0x97, 0xa4, 0x61, 0x2f, 0xeb, 0x60, 0xd7, 0xb1, 0x6b, 0x7b, 0xf1, 0xa7,
	0x05, 0x96, 0x97, 0xf3, 0x30, 0x89, 0x53, 0x5a, 0xc8, 0x17, 0x0c, 0xcb, 0x7f, 0x5a, 0xfa, 0x84,
	0x5d, 0x92, 0x90, 0xa0, 0x3d, 0xf4, 0xef, 0x54, 0xa2, 0x59, 0x1d, 0xb7, 0xce, 0xb6, 0x35, 0x72,
	0xd4, 0xe3, 0x73, 0xaa, 0xc7, 0xe7, 0x6c, 0x8a, 0xc7, 0x87, 0xbe, 0x02, 0xfc, 0xd3, 0x89, 0xde,
	0x34, 0xf3, 0x6e, 0x74, 0x37, 0xc2, 0x5c, 0x30, 0x6f, 0xc4, 0xa2, 0xb7, 0xcd, 0xb4, 0x5b, 0xf3,
	0x8d, 0x38, 0x1f, 0x06, 0xf7, 0x82, 0xd1, 0xbb, 0x66, 0xe2, 0x7f, 0x97, 0xd0, 0x04, 0x3d, 0x74,
	0xca, 0xfc, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x69, 0xec, 0xb3, 0xac, 0x03, 0x00,
	0x00,
}
